/**
 * Spanish UI strings for the Leads Analytics report.
 */

export const LEADS_ANALYTICS_UI = {
	PAGE_TITLE: 'Analítica de Leads',
	PAGE_SUBTITLE: 'Flujo comercial, conversión a negocio y carga por asesor',
	FILTERS_TITLE: 'Filtros del reporte',
	DATE_FROM: 'Desde',
	DATE_TO: 'Hasta',
	FOLLOW_UP_TITLE: 'Estado de seguimiento',
	FOLLOW_UP_EMPTY: 'Sin leads para el rango de fechas seleccionado',
	CONVERTED_TITLE: 'Leads con negocio creado',
	CONVERTED_TOTAL: 'Total con negocio',
	CONVERTED_EMPTY: 'Ningún lead del rango tiene un negocio asociado',
	HEATMAP_TITLE: 'Carga por Money Strategist',
	HEATMAP_OWNER_COLUMN: 'Money Strategist',
	HEATMAP_EMPTY: 'Sin asignaciones de leads en el rango seleccionado',
	UNASSIGNED_OWNER: 'Sin asignar',
	UNNAMED_LEAD: 'Sin nombre',
	COUNT_OF: 'de',
	HIERARCHY: 'Jerarquía',
	EXPAND_HIERARCHY: 'Mostrar jerarquía',
	APPLY: 'Aplicar',
	CLEAR: 'Limpiar',
	EMPTY_HIERARCHY: 'Seleccione al menos un usuario en la jerarquía',
	EXPAND_OWNER: 'Ver leads del asesor',
	COLLAPSE_OWNER: 'Ocultar leads del asesor',
	EXPAND_FUNNEL: 'Ver leads de este estado',
	COLLAPSE_FUNNEL: 'Ocultar leads de este estado',
	COLUMN_LEAD: 'Lead',
	COLUMN_OWNER: 'Asesor',
	COLUMN_OUTCOME: 'Estado',
	COLUMN_CREATED: 'Creado',
	COLUMN_ACTION: 'Acción',
	VIEW_LEAD: 'Ver lead',
	VIEW_BUSINESS: 'Ir a negocio',
	EXPAND_CONVERTED: 'Ver leads con negocio',
	COLLAPSE_CONVERTED: 'Ocultar leads con negocio',
	SEE_MORE: 'Ver más',
	REMAINING: 'restantes',
	TRUNCATED_HINT: ' — lista truncada; ajuste los filtros para ver el resto',
	ERROR_DATE_RANGE: 'La fecha de inicio debe ser anterior a la fecha fin',
	ERROR_REPORT: 'No se pudo cargar el reporte de leads',
	ERROR_CELL_LEADS: 'No se pudieron cargar los leads de este punto',
	ERROR_LEAD_DETAIL: 'No se pudo abrir el detalle del lead',
	LOADING: 'Cargando…',
	LEADS_SINGULAR: 'lead',
	LEADS_PLURAL: 'leads',
} as const
