/**
 * Spanish UI strings for Producción Real report.
 */

export const PRODUCCION_REAL_UI = {
	PAGE_TITLE: 'Producción Real',
	PAGE_SUBTITLE: 'Producción consolidada por jerarquía, filtros y moneda',
	FILTERS_TITLE: 'Filtros del reporte',
	DATE_FROM: 'Desde',
	DATE_TO: 'Hasta',
	CONTRIBUTION_TYPE: 'Tipo de Aporte',
	COMPANY: 'Compañía',
	CURRENCY: 'Moneda',
	TODAS: 'Todas',
	CLEAR: 'Limpiar',
	APPLY: 'Aplicar',
	DOWNLOAD_EXCEL: 'Descargar Excel',
	EXCEL_SUCCESS: 'Excel descargado correctamente',
	KPI_PRODUCCION_REAL: 'Producción Real',
	KPI_REGULAR: 'Regular',
	KPI_UNICO: 'Único',
	KPI_FONDEADO: 'Fondeado',
	KPI_CONVERSION: 'Conversión',
	COMPARISON_TITLE: 'Regular vs Única',
	DETAIL_TITLE: 'Detalle',
	EMPTY_TABLE: 'Sin negocios para los filtros seleccionados',
	EMPTY_HIERARCHY: 'Seleccione al menos un usuario en la jerarquía',
	LOADING: 'Cargando…',
	LOAD_MORE: 'Cargando más…',
	ERROR_CATALOGS: 'No se pudieron cargar los catálogos',
	ERROR_KPIS: 'No se pudieron cargar los indicadores',
	ERROR_DETAIL: 'No se pudo cargar el detalle',
	ERROR_DATE_RANGE: 'La fecha de inicio debe ser anterior a la fecha fin',
	COLUMN_CREATED: 'F. Creación',
	COLUMN_CLIENT: 'Cliente',
	COLUMN_AGENT: 'Agente',
	COLUMN_COMPANY: 'Compañía',
	COLUMN_PRODUCT: 'Producto',
	COLUMN_TYPE: 'Tipo',
	COLUMN_STATUS: 'Estado',
	COLUMN_VALUE: 'Valor',
	COLUMN_ISSUED: 'F. Emisión',
	COLUMN_ANCHORED: 'F. Fondeo',
	CURRENCY_ALL_TRM: 'Todas (TRM auto)',
	CURRENCY_FOREIGN: 'Moneda Extranjera',
	CURRENCY_COP: 'Peso Colombiano',
	CONTRIBUTION_REGULAR: 'Regular',
	CONTRIBUTION_UNICO: 'Único',
	HIERARCHY: 'Jerarquía',
	NEGOCIO_SINGULAR: 'negocio',
	NEGOCIOS_PLURAL: 'negocios',
} as const
