import { prisma } from '@/lib/prisma'

/**
 * Acciones de auditoría
 */
export enum AuditAction {
	LOGIN = 'LOGIN',
	LOGOUT = 'LOGOUT',
	ACCESS_DENIED = 'ACCESS_DENIED',
	ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
	INVALID_DOMAIN = 'INVALID_DOMAIN',
	USER_CREATED = 'USER_CREATED',
	USER_ACTIVATED = 'USER_ACTIVATED',
	USER_DEACTIVATED = 'USER_DEACTIVATED',
	ROLE_CHANGED = 'ROLE_CHANGED',
	USER_CREATION_ERROR = 'USER_CREATION_ERROR',
	BUSINESS_UPDATED = 'BUSINESS_UPDATED',
	BUSINESS_CANCELLED = 'BUSINESS_CANCELLED',
	BUSINESS_ELIMINATED = 'BUSINESS_ELIMINATED',
	BUSINESS_FUNDED = 'BUSINESS_FUNDED',
	BUSINESS_PAYMENT_FUNDED = 'BUSINESS_PAYMENT_FUNDED',
	COMPANY_CREATED = 'COMPANY_CREATED',
	COMPANY_UPDATED = 'COMPANY_UPDATED',
	COMPANY_DELETED = 'COMPANY_DELETED',
	COMPANY_STATUS_CHANGED = 'COMPANY_STATUS_CHANGED',
	PRODUCT_CREATED = 'PRODUCT_CREATED',
	PRODUCT_UPDATED = 'PRODUCT_UPDATED',
	PRODUCT_DELETED = 'PRODUCT_DELETED',
	CLIENT_ORIGIN_CREATED = 'CLIENT_ORIGIN_CREATED',
	CLIENT_ORIGIN_UPDATED = 'CLIENT_ORIGIN_UPDATED',
	CLIENT_ORIGIN_DELETED = 'CLIENT_ORIGIN_DELETED',
	CLIENT_UPDATED = 'CLIENT_UPDATED',
	IMPORT_ERROR = 'IMPORT_ERROR',
	DISCOUNT_CREATED = 'DISCOUNT_CREATED',
	DISCOUNT_INACTIVATED = 'DISCOUNT_INACTIVATED',
	COMMISSION_SETTLED = 'COMMISSION_SETTLED',
	COMMISSION_LAGGED = 'COMMISSION_LAGGED',
	LEVEL_CREATED = 'LEVEL_CREATED',
	LEVEL_UPDATED = 'LEVEL_UPDATED',
	LEVEL_DEACTIVATED = 'LEVEL_DEACTIVATED',
	CATEGORY_CREATED = 'CATEGORY_CREATED',
	CATEGORY_UPDATED = 'CATEGORY_UPDATED',
	CATEGORY_DEACTIVATED = 'CATEGORY_DEACTIVATED',
	PRODUCT_CONFIGURATION_CREATED = 'PRODUCT_CONFIGURATION_CREATED',
	PRODUCT_CONFIGURATION_UPDATED = 'PRODUCT_CONFIGURATION_UPDATED',
	PRODUCT_CONFIGURATION_DEACTIVATED = 'PRODUCT_CONFIGURATION_DEACTIVATED',
	DISTRIBUTION_COMMISSION_CREATED = 'DISTRIBUTION_COMMISSION_CREATED',
	DISTRIBUTION_COMMISSION_UPDATED = 'DISTRIBUTION_COMMISSION_UPDATED',
	DISTRIBUTION_COMMISSION_ACTIVATED = 'DISTRIBUTION_COMMISSION_ACTIVATED',
	DISTRIBUTION_COMMISSION_DEACTIVATED = 'DISTRIBUTION_COMMISSION_DEACTIVATED',
	COMPROBANTE_UPLOADED = 'COMPROBANTE_UPLOADED',
	COMPROBANTE_DEACTIVATED = 'COMPROBANTE_DEACTIVATED',
	APORTE_CARTERA_MARKED = 'APORTE_CARTERA_MARKED',
	APORTE_CARTERA_UNMARKED = 'APORTE_CARTERA_UNMARKED',
	APORTE_PAGO_ANTICIPADO_MARKED = 'APORTE_PAGO_ANTICIPADO_MARKED',
	APORTE_CARTERA_PAGADO = 'APORTE_CARTERA_PAGADO',
	APORTE_PRIMER_PAGO_FONDEADO = 'APORTE_PRIMER_PAGO_FONDEADO',
	PAYMENT_CRON_FUNDED = 'PAYMENT_CRON_FUNDED',
	PAYMENT_MIGRATION_RESET = 'PAYMENT_MIGRATION_RESET',
	BUSINESS_MIGRATION_FONDEADO = 'BUSINESS_MIGRATION_FONDEADO',
	BUSINESS_CRON_FONDEADO = 'BUSINESS_CRON_FONDEADO',
	BUSINESS_CARTERA = 'BUSINESS_CARTERA',
	BUSINESS_REFONDEADO = 'BUSINESS_REFONDEADO',
	BUSINESS_EXPORTED = 'BUSINESS_EXPORTED',
	BUSINESS_DATE_ANCHORED_UPDATED = 'BUSINESS_DATE_ANCHORED_UPDATED',
	BUSINESS_REMEDIATION_REVERTED = 'BUSINESS_REMEDIATION_REVERTED',
	COMMENT_CREATED = 'COMMENT_CREATED',
	BUSINESS_NOVEDAD_MARKED = 'BUSINESS_NOVEDAD_MARKED',
	BUSINESS_NOVEDAD_UNMARKED = 'BUSINESS_NOVEDAD_UNMARKED',
	BUSINESS_NOVEDAD_RESOLVED = 'BUSINESS_NOVEDAD_RESOLVED',
	LEAD_CREATED = 'LEAD_CREATED',
	LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',
	LEAD_OWNER_ASSIGNED = 'LEAD_OWNER_ASSIGNED',
	LEAD_OWNER_UNRESOLVED = 'LEAD_OWNER_UNRESOLVED',
	LEAD_CONVERTED_TO_BUSINESS = 'LEAD_CONVERTED_TO_BUSINESS',
	LEAD_FUNNEL_COLUMN_CREATED = 'LEAD_FUNNEL_COLUMN_CREATED',
	LEAD_FUNNEL_COLUMN_UPDATED = 'LEAD_FUNNEL_COLUMN_UPDATED',
	LEAD_OUTCOME_STATUS_CHANGED = 'LEAD_OUTCOME_STATUS_CHANGED',
	LEAD_OUTCOME_STATUS_UNRESOLVED = 'LEAD_OUTCOME_STATUS_UNRESOLVED',
	LEAD_OUTCOME_STATUS_LOCKED = 'LEAD_OUTCOME_STATUS_LOCKED',
}

/**
 * Parámetros para registrar un log de auditoría
 */
export interface AuditLogParams {
	userId?: number
	roleId?: number
	action: AuditAction
	email?: string
	ipAddress?: string
	userAgent?: string
	details?: string
}

/**
 * Registra un evento en el log de auditoría
 */
export async function logAuditEvent(params: AuditLogParams): Promise<void> {
	try {
		await prisma.auditLog.create({
			data: {
				idUser: params.userId,
				idRole: params.roleId,
				action: params.action,
				email: params.email,
				ipAddress: params.ipAddress,
				userAgent: params.userAgent,
				details: params.details,
			},
		})
	} catch (error) {
		// No lanzar error para no interrumpir el flujo de autenticación
		// Solo registrar en consola para debugging
		console.error('Error logging audit event:', error)
	}
}

/**
 * Obtiene la IP del cliente desde headers
 */
export function getClientIp(headers: Headers): string | undefined {
	// Intentar obtener IP de headers comunes
	const forwarded = headers.get('x-forwarded-for')
	if (forwarded) {
		return forwarded.split(',')[0].trim()
	}

	const realIp = headers.get('x-real-ip')
	if (realIp) {
		return realIp
	}

	return undefined
}

/**
 * Obtiene el User-Agent desde headers
 */
export function getUserAgent(headers: Headers): string | undefined {
	return headers.get('user-agent') || undefined
}
